# Rate at which the ramdom sampled sized topics are sent.
publisher_rate: 15.0 

distributions:
  - distribution1:
    - service_name: "poisson_lambda_20_0"
    - type_of_response: "float"           #float or int
    - distribution_type: "poisson"
    - lambda: 20.0   #Mean of number of events per timestep

  - distribution2:
    - service_name: "poisson_lambda_15_0"
    - type_of_response: "float"           #float or int
    - distribution_type: "poisson"
    - lambda: 15.0   #Mean of number of events per timestep

  - distribution3:
    - service_name: "poisson_lambda_3_0"
    - type_of_response: "float"           #float or int
    - distribution_type: "poisson"
    - lambda: 3.0   #Mean of number of events per timestep

  - distribution4:
    - service_name: "real_queue_arrival_evaluation"
    - type_of_response: "float"           #float or int
    - distribution_type: "poisson"
    - lambda: 372.0   #Mean of number of events per timestep
  
  - distribution5:
    - topic_name: "topic_poisson_lambda_5_0"
    - distribution_type: "poisson"
    - lambda: 5.0   #Mean of number of events per timestep

  - distribution5:
    - topic_name: "mock_real_queue_0_arrival_topic"
    - distribution_type: "poisson"
    - lambda: 60.0   #Mean of number of events per timestep
  
  - distribution6:
    - service_name: "poisson_lambda_6_0"
    - type_of_response: "int"           #float or int
    - distribution_type: "poisson"
    - lambda: 4.0   #Mean of number of events per timestep
  
  - distribution6:
    - service_name: "poisson_lambda_9_0"
    - type_of_response: "float"           #float or int
    - distribution_type: "poisson"
    - lambda: 9.0   #Mean of number of events per timestep

  - distribution7:
    - service_name: "bernoulli_0"
    - type_of_response: "int"           #float or int
    - distribution_type: "bernoulli"
    - high_value: 100.0   # Value when the discrete system is in its "on" state.
    - low_value: 0.0      # Value when the discrete system is in its "off" state.
    - probability_of_high_value: 0.03  # Probability between 0 and 1 that the state will be on when evaluated.